Поиск конфликтов в двух журналах транзакций, локальный случай
d-r-q/qbit pull request #130
Opened 2020-12-11 16:46 UTC by ldadima

2021-02-07 04:41 UTC, d-r-q requested changes

2021-02-07 04:41 UTC, d-r-q commented on qbit-core/src/commonTest/kotlin/qbit/resolving/TestUtils.kt
> +    val root = Root(nullHash, testDbUuid, testTimestamp, testNodeData)
Я бы тут подумал о том, чтобы отдельно построить граф и отдельно посчитать для него мапу глубин - стабильнее будет.
И для графа можно ваще DSL придумать. Тут думать надо, но можно попробовать чё-нить в таком духе:
```kotlin
val root = Root(nullHash, testDbUuid, testTimestamp, testNodeData)
val (leaf1, leaf2, leaf3, leaf4, leaf5, leaf6) = root.append(testNodeData x 6 раз)
val merge1 = (leaf1 to leaf2).merge(testNodeData)
val leaf7 = leaf3.append(testNodeData)
и т.п.
```
Но это всё понятно должно быть экстеншн функциями.
Либо можно чё-нить в таком духе: https://github.com/moaxcp/graph-dsl

Но ДСЛ - это опционально

2021-02-07 04:41 UTC, d-r-q commented on qbit-core/src/commonTest/kotlin/qbit/FunTest.kt
> +            conn.db {
Это вроде можно смёржить

2021-02-07 04:41 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/resolving/ConflictResolving.kt
> +    conflictEavs1: HashMap<Eav, HasConflictResult>,
1 - кажись лишнее

2021-02-07 04:41 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/resolving/ConflictResolving.kt
> +    conflictEavs1: HashMap<Eav, HasConflictResult>,
И это опять у тебя аут-параметр. Никогда не используй HashMap|MutableMap|ArrayList|MutableList в параметрах.

2021-02-07 04:41 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/resolving/ConflictResolving.kt
> +    entitiesMap: HashMap<Gid, MutableList<Eav>>
И это тоже

2021-02-07 04:41 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/resolving/ConflictResolving.kt
> +internal fun createRawEntitiesWithoutConflicts(
Это императивный адок, который запаришься читать. Давай сначала уберём аут-парметры, потом ещё раз гляну

2021-02-07 04:41 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/resolving/ConflictResolving.kt
> +    if (eav1.gid == eav2.gid && eav1.attr == eav2.attr) {
Это кажись можно заменить на:
```kotlin
when {
  eav1 == eav2 -> NO_CONFLICT
  eav1 equalAttr eav2 -> CONFLICT
  else -> NO_CHANGES
}

infux fun Eav.equalAttr(eav: Eav) = eav1.gid == eav2.gid && eav1.attr == eav2.attr
```

2021-02-07 04:41 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/resolving/ConflictResolving.kt
> +    internal val conflictsMap: Map<Gid, ConflictGid> = HashMap()
А если у тебя несколько конфликтов для одного гида?

2021-02-07 04:41 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/resolving/ConflictResolving.kt
> +    for (node in nodes) {
Чёт это какая-то имеративаная жизнь
Надо это линеаризовать и сделать в декларативно стиле на множествах
чё-нить в духе:
```kotlin
data class PersistedEav(val eav: Eav, timestamp: Long, node: Hash)
data class GidAttr(val gid: Gid, val attr: Attr)
val entityAttrsA: Map<GidAttr, List<PersistedEav>> = nodes.flatMap { n -> n.map { PersistedEav(it, n.timestamp, n.hash) } }.groupBy { it.eav.gidAttr }
val entityAttrsB : Map<GidAttr, List<PersistedEav>> = newModes.flatMap { n -> n.map { PersistedEav(it, n.timestamp, n.hash) } }.groupBy { it.eav.gidAttr}
val writesIntersection = entityAttrsA.keySet().intersection(entityAttrsB.keySet())
if (writesIntersection.isEmpty()) {
  return NO_CONFLICTS
}
val conflictingWrites = writesIntersection.filter { entityAttrsA[it].last != entityAttrsB[it].last }
if (conflictingWrites.isEmpty()) {
  return NO_CHANGES
}
retrun ConflictResult(CONFLICT, conflictingWrites)
```

2021-02-08 12:16 UTC, ldadima commented on qbit-core/src/commonMain/kotlin/qbit/resolving/ConflictResolving.kt
> +    internal val conflictsMap: Map<Gid, ConflictGid> = HashMap()
Сюда записывается есть ли в гиде хотя бы один конфликт. А дальше уже определяются еавы с этим конфликтом

2021-02-08 12:17 UTC, ldadima commented on qbit-core/src/commonMain/kotlin/qbit/resolving/ConflictResolving.kt
> +            return when (node1) {
Какой именно кусок? начиная со второго when?

2021-02-08 12:21 UTC, ldadima commented on qbit-core/src/commonMain/kotlin/qbit/resolving/ConflictResolving.kt
> +                    val n1 = findBaseNode(node1.parent1, node2, nodesDepth)
Думаю что это приведет к ошибке, их общая база может оказаться между мёржем и его базой. Например на картинке.
![dvUJi8jCZuk](https://user-images.githubusercontent.com/48554952/107218875-d2aef800-6a42-11eb-9e77-06db81469f50.jpg)

2021-02-08 12:22 UTC, ldadima commented on qbit-core/src/commonMain/kotlin/qbit/resolving/ConflictResolving.kt
> +                is Merge -> {
не вижу проблемы, следую дальше по рекурсии - она обработается как нужно

2021-02-08 12:24 UTC, ldadima commented on qbit-core/src/commonMain/kotlin/qbit/resolving/ConflictResolving.kt
> +                node1 is Leaf && node2 is Merge -> {
Кажется что нет node2.parent1 и node2.parent2 в первом случае и тоже самое с node1 далее. Узлы вроде же разные. Возмножно я не понял

2021-02-08 14:28 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/resolving/ConflictResolving.kt
> +    internal val conflictsMap: Map<Gid, ConflictGid> = HashMap()
Ну у тебя там в 87 строке вроде не учитывается случай, когда было два конфликта в 4ёх разных нодах, не?

2021-02-08 14:28 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/resolving/ConflictResolving.kt
> +            return when (node1) {
Да

2021-02-09 02:44 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/resolving/ConflictResolving.kt
> +            return when (node1) {
да

2021-02-09 02:48 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/resolving/ConflictResolving.kt
> +                    val n1 = findBaseNode(node1.parent1, node2, nodesDepth)
ну вот да. А что если конфликт в этих нодах:
![image](https://user-images.githubusercontent.com/1336130/107308796-daf74980-6abb-11eb-884e-85b40101a5b9.png)

2021-02-09 02:49 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/resolving/ConflictResolving.kt
> +                is Merge -> {
Ладно, давай пока оставим так, потом как приберёмся ещё раз гляну

2021-02-09 02:51 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/resolving/ConflictResolving.kt
> +                    listBases.add(findBaseNode(node1.parent1, node2.parent1, nodesDepth))
В прошлый раз забыл написать - прежде чем чинить надо было написать падающий тест. А теперь просто надо написать тест на эту часть.

2021-02-21 07:34 UTC, d-r-q commented on qbit-core/src/commonTest/kotlin/qbit/resolving/TestUtils.kt
> +    val root = Root(nullHash, testDbUuid, testTimestamp, testNodeData)
@ldadima
У тебя подсчёт глубин остался ручной, давай его автоматизируем

2021-02-21 10:29 UTC, d-r-q requested changes

2021-02-21 10:29 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/resolving/ConflictResolving.kt
> +internal fun hasConflict(
Надо эту функцию ещё разбить:
```kotlin

fun logsDiff(baseLog: TrxLog, logA: TrxLog, logB: TrxLog): LogsDiff {
   // первая часть hasConflict
}

data class LogsDiff(val allWrites: Set<GidAttr>, val writesFromA: Map<GidAttr, List<PersistedEav>, val writesFromB: Map<GidAttr, List<PersistedEav>>) {

    fun hasConflicts(): HasConflictResult = // вторая часть hasConfllicts

    fun merge(resolve: (List<PersistedEav>, List<PersistedEav>) -> Eav): Map<Gid, RawEntity> {
        // сгруппировать allWrites по git
        // для каждого гида, пробежаться по списку GidAttr
        // для каждого gidAttr взять List<PersistedEav> из а и б, если он один - вернуть взять еав, если их два - передать их в резолв и взять еав оттуда
        // собрать eav-ы в RawEntity
        // List<RawEntity>.associateBy { it.first.gid }
    }

}

```

2021-02-22 15:49 UTC, ldadima commented on qbit-core/src/commonMain/kotlin/qbit/resolving/ConflictResolving.kt
> +private fun deleteNoConflictGids(
Мне функции убрать и просто заинлайнить или как?

2021-02-22 15:51 UTC, ldadima commented on qbit-core/src/commonTest/kotlin/qbit/resolving/TestUtils.kt
> +    val root = Root(nullHash, testDbUuid, testTimestamp, testNodeData)
Хм, писать в тестах код с какой-то логикой, не странно? Ее по хорошему тогда тоже тестировать

2021-02-23 03:31 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/resolving/ConflictResolving.kt
> +private fun deleteNoConflictGids(
Оригинальная задумка была заинлайнить, но посмотри, может этот коммент потеряет актуальность после рефакторинга к LogsDiff

2021-02-23 03:35 UTC, d-r-q commented on qbit-core/src/commonTest/kotlin/qbit/resolving/TestUtils.kt
> +    val root = Root(nullHash, testDbUuid, testTimestamp, testNodeData)
Это у тебя не совсем тесты, а тестовая фикстура.
И если логика позволяет тебе повысить читаемость фикстуры, то это норм.
Тестировать её отдельно не надо

2021-02-23 08:24 UTC, ldadima commented on qbit-core/src/commonMain/kotlin/qbit/resolving/ConflictResolving.kt
> +    entityAttrsB = deleteNoConflictGids(entityAttrsB, conflictingWrites)
Не понимаю проблемы

2021-03-14 03:33 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/resolving/ConflictResolving.kt
> +        val gidAttrsGroupByGid = (writesFromA.keys + writesFromB.keys).groupBy { it.gid }
Тебе тут разве не intersect нужен?
Зачем тебе не конфликтующие ключи рассматривать?

2021-03-14 03:37 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/resolving/ConflictResolving.kt
> +//              Second variant (этот вариант, по идее, правильнее, т.к. не зависит от реализации resolve()
Не понял чем он правильнее. И тут он не точно зависит от реализации резолва - к этому варианту реализация lww приколочена гвоздями

2021-03-14 03:40 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/Conn.kt
> +            newLog.mergeWith(this.trxLog,
Игноришь возвращаемое значение mergeWith
Надо покрыть тестом

2021-03-14 03:42 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/trx/TrxLog.kt
> +        val anotherHead = resolveNode(NodeRef(trxLog.hash))
Зачем тут resolveNode? В Merge подаётся Node и NodeRef это подтип Node

2021-03-14 03:42 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/trx/TrxLog.kt
> +        e: Collection<Eav>,
Что значит е?

2021-03-14 04:02 UTC, d-r-q requested changes

2021-03-14 04:02 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/trx/TrxLog.kt
> +                fromNode.hash == to -> continue
Почему не break? Он вроде лучше передаёт намерение

2021-03-14 04:02 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/trx/TrxLog.kt
> +                fromNode is Merge -> throw UnsupportedOperationException("Merges not yet supported")
Ну так-то поддержаны, надо запилить.
Ну и без мёржей в всё этой конструкции смысла нет - достаточно просто по списку пробежаться

2021-03-22 14:30 UTC, ldadima commented on qbit-core/src/commonMain/kotlin/qbit/Conn.kt
> +            newLog.mergeWith(this.trxLog,
Тест на то, правильный ли журнал возвращается? Как тест для функции merge в строке 143

2021-03-22 14:52 UTC, ldadima commented on qbit-core/src/commonMain/kotlin/qbit/resolving/ConflictResolving.kt
> +        val gidAttrsGroupByGid = (writesFromA.keys + writesFromB.keys).groupBy { it.gid }
Если сделать intersect, то теряются неконфликтующие изменения. Как раз по тому алгоритму, что вы ранее предлагали, при пустом втором множестве, по сути, не происходит разрешения конфликтов между ветками журнала, только внутри ветки (выбирается последнее изменение атрибута). Из этого получается, что я слишком использую текущую реализация resolve в своих целях.

2021-03-22 14:52 UTC, ldadima commented on qbit-core/src/commonMain/kotlin/qbit/resolving/ConflictResolving.kt
> +//              Second variant (этот вариант, по идее, правильнее, т.к. не зависит от реализации resolve()
В итоге, как понимаю ни один вариант не подходит?

2021-03-22 14:55 UTC, ldadima commented on qbit-core/src/commonMain/kotlin/qbit/trx/TrxLog.kt
> +        resolveNode: (Node<Hash>) -> NodeVal<Hash>?
Если так можно (что внутри Merge узла родитель - NodeRef), то ок

2021-03-22 14:56 UTC, ldadima commented on qbit-core/src/commonMain/kotlin/qbit/trx/TrxLog.kt
> +        resolveNode: (Node<Hash>) -> NodeVal<Hash>?
Только не понимаю зачем передавать NodeRef, можно как и сейчас просто создать его внутри метода

2021-03-22 15:08 UTC, ldadima commented on qbit-core/src/commonMain/kotlin/qbit/Conn.kt
> +            newLog.mergeWith(this.trxLog,
Или же проверка на то изменился ли журнал?
обновил строчку так:
`this.trxLog = newLog.mergeWith(this.trxLog,
                eavs)`

2021-03-28 05:00 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/Conn.kt
> +            newLog.mergeWith(this.trxLog,
Нужен тест на то, что уже закомиченные ноды не теряются.
Тебе надо откатить правку, написать падающий тест и убедиться, что он чинится твоей правкой.

Падающий тест, видимо:
1) Начанть транзакцию 1 и 2
2) Закоммитать транзакцию 1
3) Закоммитать транзакцию 2
4) Начать и закоммитать транзакцию 3
5) переоткрыть БД, посмотреть, что в ней есть данные из всех транзакций. Щяс там кажись потеряется транзакция 1, т.к. после коммита транзакции 2 она станет головой, а не мёрж, и транзакция 3 будет от неё

2021-03-28 05:36 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/resolving/ConflictResolving.kt
> +        val gidAttrsGroupByGid = (writesFromA.keys + writesFromB.keys).groupBy { it.gid }
> то теряются неконфликтующие изменения
Это потому что ты в Conn.update игноришь одну из баз.

> Как раз по тому алгоритму, что вы ранее предлагали
То что я предлагаю - это общее (и не факт что вообще правильное) направление.

> Из этого получается, что я слишком использую текущую реализация resolve в своих целях.
Это я вообще не понял.

И того:
1) Узел мёржа должен содержать только конфилктующие сущности
2) При этом и инкрементальная бд (наращивая по мере коммитов) и первоначальная бд при открытии коммитов (получаемая из чтения журнала) должны содержать все сущности

2021-03-28 05:38 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/resolving/ConflictResolving.kt
> +//              Second variant (этот вариант, по идее, правильнее, т.к. не зависит от реализации resolve()
Да, нужен вариант, который создаст только конфликтуюище сущности с помощью функции resolve

2021-03-28 05:40 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/trx/TrxLog.kt
> +        resolveNode: (Node<Hash>) -> NodeVal<Hash>?
> Если так можно (что внутри Merge узла родитель - NodeRef), то ок

да, должно быть можно

> Только не понимаю зачем передавать NodeRef, можно как и сейчас просто создать его внутри метода

ага, да

2021-03-28 05:44 UTC, d-r-q commented
И, кстати, отдельная проблема - кажись щяс если в параллельных транзакциях создать по новой сущности, то им сгенеряется один и тот же еид и после мёржа они смёржатся в одну. Надо написать на это тест (который вставляет 2 разных сущности с двумя разными уникальными атрибутами и разными обычными полями, потом находит сущности по ключам и проверяет, что обе находятся и что у них только "свои" атрибуты). А потом пофиксать. Как фиксать - подумай сначала сам, предложи варианты. Если не получиться - пиши, подумаем вместе

2021-04-28 03:50 UTC, d-r-q commented
> И, кстати, отдельная проблема - кажись щяс если в параллельных транзакциях создать по новой сущности, то им сгенеряется один и тот же еид и после мёржа они смёржатся в одну. Надо написать на это тест (который вставляет 2 разных сущности с двумя разными уникальными атрибутами и разными обычными полями, потом находит сущности по ключам и проверяет, что обе находятся и что у них только "свои" атрибуты). А потом пофиксать. Как фиксать - подумай сначала сам, предложи варианты. Если не получиться - пиши, подумаем вместе

@ldadima вот эту штуку вроде не сделал

2021-04-28 04:54 UTC, d-r-q requested changes

2021-04-28 04:54 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/Conn.kt
> +            this.trxLog = newLog
Симметрия - очень хорошее свойство кода. Тут первая мысль, что потерял обновление журнала. Но нет.
Но в следующий раз, когда я буду что-то делать с журналом - вопрос догадаюсь ли я подправить строку в предыдущем ифе

2021-04-28 04:54 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/Conn.kt
> +        var mergeDb : InternalDb? = null
var- почти всегда плохо. var = null - всегда плохо

2021-05-01 08:28 UTC, d-r-q requested changes

2021-05-01 08:28 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/trx/TrxLog.kt
> +            nodesDepth[trxLog.hash]?:trxLog.getNodesDepth()[trxLog.hash]?:throw AssertionError("Should never happen with depth for node: ${trxLog.hash}"))
Тут чёт какой-то адок с форматированием

2021-05-01 08:28 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/trx/TrxLog.kt
> +    private fun updateMapOfNodesDepth(newHead: NodeVal<Hash>, depthAnotherParent: Int = 0): Map<Hash, Int> {
Тут перемешано два разных уровня абстракции - нода и глубина
плюс глубина нужна только одной из веток
замени depthAnotherParent на nodeDepth: (Hash) -> Long, выдрав его из (nodesDepth + trxLogNodesDepth)::getValue.

2021-05-01 08:28 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/trx/TrxLog.kt
> +            nodesDepth[trxLog.hash]?:trxLog.getNodesDepth()[trxLog.hash]?:throw AssertionError("Should never happen with depth for node: ${trxLog.hash}"))
И какой тут вообще смысл смотреть в nodesDepth[trxLog.hash]?

2021-05-01 08:28 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/trx/TrxLog.kt
> +            nodesDepth[trxLog.hash]?:trxLog.getNodesDepth()[trxLog.hash]?:throw AssertionError("Should never happen with depth for node: ${trxLog.hash}"))
Что именно Should never happen with depth for node xxx?

2021-05-01 08:28 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/trx/TrxLog.kt
> +                    nodesBetween.add(0, fromNode)
Какая сложность этой операции?

2021-05-01 08:28 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/trx/TrxLog.kt
> +                    val parents1 = nodesBetween(parent1, fromNode.base.hash, resolveNode)
Чёт у тебя тут и ручной стэк и рекурсия, тут точно нельзя чем-то одним обойтись?

2021-05-01 08:28 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/trx/TrxLog.kt
> +    private fun nodesBetween(from: NodeVal<Hash>, to: Hash, resolveNode: (Node<Hash>) -> NodeVal<Hash>?): List<NodeVal<Hash>>{
И чёт тут кажись не нужен resolve
можно вернуть List<NodeRef>, а потом, при необходимости его порезолвать

2021-05-01 13:13 UTC, ldadima commented on qbit-core/src/commonMain/kotlin/qbit/trx/TrxLog.kt
> +                    nodesBetween.add(0, fromNode)
O(n). Ну в любом случае я переписываю на реализацию через рекурсию

2021-05-02 06:05 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/trx/TrxLog.kt
> +        val newNodesDepth = updateMapOfNodesDepth(newHead) { 0 }
А это зачем? передавай так же nodesDepth::getValue

2021-05-02 09:03 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/trx/TrxLog.kt
> +    private fun nodesBetween(from: Node<Hash>, to: Hash): List<Node<Hash>>{
Я чёт пропустил, что ты тут задублировал Indexer
Надо этот алгоритм выделить в одно место, кажись TrxLog и в иделе возврат поменять на Flow<Node<Hash>>. Но это после бага с конфликтом генерации идов

2021-05-02 10:18 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/trx/TrxLog.kt
> +    private fun nodesBetween(from: Node<Hash>, to: Hash): List<Node<Hash>>{
Вот примерно так надо сделать:
```kotlin
    private fun nodesBetween(base: Node<Hash>, head: Node<Hash>): List<Node<Hash>> {
        return runBlocking {
            test(base, head).toList()
        }
    }

    private fun test(base: Node<Hash>, head: Node<Hash>): Flow<Node<Hash>> {
        return flow { impl(base, head) }
    }

    private suspend fun FlowCollector<Node<Hash>>.impl(base: Node<Hash>, head: Node<Hash>) {
        when (head) {
            base -> return
            is Root -> return
            is Leaf -> {
                impl(base, head.parent)
                emit(head)
            }
            is Merge -> {
                // nodes should be emitted in order of ascending distance from root
                // so if there is no base in merge branches, then nodes before merge base should be emitted
                // therefore it's necessary to check is branches flows contains base before emitting them
                val firstBranch = flow { impl(head.base, head.parent1) }
                val secondBranch = flow { impl(head.base, head.parent2) }
                val notFoundInFirstBranch = firstBranch.firstOrNull { it == base } == null
                val notFoundInSecondBranch = !notFoundInFirstBranch &&
                        secondBranch.firstOrNull { it == base } == null
                if (notFoundInFirstBranch && notFoundInSecondBranch) {
                    // emit nodes before split, if branches do not contain base
                    impl(base, head.base)
                }
                if (notFoundInSecondBranch) {
                    // emit first branch, if head not in second branch (i.e. in first branch or before split)
                    emitAll(firstBranch)
                }
                if (notFoundInFirstBranch) {
                    // emit second branch, if head not in second branch (i.e. in first branch or before split)
                    emitAll(secondBranch)
                }
                // emit merge node always
                emit(head)
            }
            is NodeRef -> impl(
                base,
                storage.load(head) ?: throw QBitException("Corrupted trx graph, cannot resolve $head")
            )
        }
    }
```

Ток:
1) у тебя сейчас мёрж в nodesBetween тестами не покрыт, так что хз работает ли
2) вместод листа надо будет вернуть Flow и соответсвенно runBlocking выкинуть
3) ну и код утащить в TrxLog

2021-05-02 10:22 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/trx/TrxLog.kt
> +    private fun nodesBetween(from: Node<Hash>, to: Hash): List<Node<Hash>>{
4. ну и test заинлайнить

2021-05-02 13:48 UTC, ldadima commented on qbit-core/src/commonMain/kotlin/qbit/trx/TrxLog.kt
> +    private fun nodesBetween(from: Node<Hash>, to: Hash): List<Node<Hash>>{
Как раз хотел спросить про это при обсуждении. Думал в Indexer можно как-то засунуть TrxLog или метод сделать статическим. Ну да ладно

2021-05-10 00:31 UTC, d-r-q requested changes

2021-05-10 00:31 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/trx/Trx.kt
> +//    private val gids = Gid(inst.iid, inst.nextEid).nextGids()
Это надо выкинуть

2021-05-10 00:31 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/Conn.kt
> +    }
это надо заменить на
```kotlin
override fun next(): Gid =
    return Gid(inst.iid, atomicEid.incrementAndGet())
```

2021-05-10 00:31 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/Conn.kt
> +class GidSequence(private val inst: Instance): Iterator<Gid>{
Тут надо:
1) Instance заменить на два инта - иид и еид.
2) класс сделать internal
3) вынести его в собственный файл и утащить в пакет trx

2021-05-10 00:31 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/Conn.kt
> +    private val gidSequence: GidSequence = GidSequence(db.pull(Gid(dbUuid.iid, theInstanceEid))!!)
Так ты сможешь Instance на инты разобрать:
```kotlin
private val gidSequence: GidSequence = with(db.pull<Instance>(Gid(dbUuid.iid, theInstanceEid))) {
    GidSequence(this ?: throw QBitException("Corrupted DB - the instance entity not found"))
}
```

И !! можно использовать **только** в одном случае - в отличае от компилятора, человек может глядя в код текущей функции гарантировать, что NPE не будет (выше была проверка непонятная компилятору, или из мапы достаётся ключ, который только что туда положили).

2021-05-10 00:31 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/resolving/ConflictResolving.kt
> +        (eavsFromA + eavsFromB).maxByOrNull { it.eav.value as Int }!!.eav
У тебя этот код игнорируется.
Давай напишем тест, который это отловит

2021-05-10 00:31 UTC, d-r-q commented on qbit-core/src/commonMain/kotlin/qbit/resolving/ConflictResolving.kt
>      } else {
А потом всё это так переписать:
```kotlin
internal fun lastWriterWinsResolve(resolveAttrName: (String) -> Attr<Any>?): (List<PersistedEav>, List<PersistedEav>) -> List<Eav> =
    { eavsFromA, eavsFromB ->
        require(eavsFromA.isNotEmpty()) { "eavsFromA should be not empty" }
        require(eavsFromB.isNotEmpty()) { "eavsFromB should be not empty" }

        val attr = resolveAttrName(eavsFromA[0].eav.attr)
            ?: throw IllegalArgumentException("Cannot resolve ${eavsFromA[0].eav.attr}")

        when {
            // temporary dirty hack until crdt counter or custom resolution strategy support is implemented
            attr == Instances.nextEid -> listOf((eavsFromA + eavsFromB).maxByOrNull { it.eav.value as Int }!!.eav)
            attr.list -> (eavsFromA + eavsFromB).map { it.eav }.distinct()
            else -> listOf((eavsFromA + eavsFromB).maxByOrNull { it.timestamp }!!.eav)
        }
    }
```

2021-06-29 01:34 UTC, d-r-q approved these changes

2021-06-29 01:35 UTC, merged